#!/bin/bash

# Script for collecting coverage only for changed files

# Function to convert file path to Python module notation
convert_path_to_module() {
    local path="$1"
    # Replace slashes with dots and remove the .py extension
    echo "${path//\//.}" | sed 's/\.py$//'
}

git fetch
MERGE_BASE_COMMIT=$(git merge-base HEAD origin/master)

echo "Collecting coverage for files modified after commit:"
git --no-pager log -n 1 $MERGE_BASE_COMMIT

echo
MODIFIED_FILES=$(git diff --name-only $MERGE_BASE_COMMIT | grep '.py$' | grep -v '^test')
echo "Changed Python files:"
echo $MODIFIED_FILES

echo
echo "Creating .temp_coveragerc config..."
TEMP_COVERAGERC=.temp_coveragerc
cp .coveragerc "$TEMP_COVERAGERC"
echo >> "$TEMP_COVERAGERC"
echo "; Autogenerated based on git diff" >> "$TEMP_COVERAGERC"
echo "source =" >> "$TEMP_COVERAGERC"
for file in $MODIFIED_FILES; do
    echo "    $(convert_path_to_module "$file")" >> "$TEMP_COVERAGERC"
done

echo
echo "Running tests..."
python3 -m coverage run --rcfile=.temp_coveragerc -m pytest test -v -m "CI"