# TODO consider creating DecomposerSettings data class to allow injecting non-global settings

HASH_PRIME_MODULUS = 2147483647
MIN_LSH_BUCKET_SIZE = 3
SMALL_BUCKET_ID = -1
HASH_FUNCTIONS_COUNT = 3
MIN_REDUCTION_RATIO = 0.05
MAX_SIZE_RATIO = 0.3

PROTOTYPE_MIN_VALUES_PER_ROW = 5
PROTOTYPE_OUTLIER_THRESHOLD = 0.05
PROTOTYPE_MIN_LSH_BUCKET_SIZE = 5
