name: Code style check

on: [ push, pull_request ]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install .
          python -m pip list

      - name: Install pre-commit
        run: |
          pre-commit install

      - name: Run black
        run: |
          pre-commit run --all-files --color always --verbose --show-diff-on-failure
